### ISSUE TITLE
SubClaim

### ISSUE THREAD

**Issue by evernife** [KaiKikuchi/GPPRealEstate#1]
I could not create an issue there, i dont know why. 
But, i was testing, i think the only problem is not being able to sell subclaims, selling normal claims is already possible, but, subclaims is not possible.

I get this: The listed player does not have the right to sell/lease this claim!

I tried to add the permissions:
gprealestate.subclaim.buy
gprealestate.subclaim.sell

And even OP players can't sell subclaims

There is no server log, just the normal ForgeRestrictor Confiscation
(When selling the normal claim this appears too, so i dont think is the forge restrictors fault.)

*21.09 15:00:52 [Server] INFO [ForgeRestrictor] Confiscated Bruninho items for 3 ticks*

**Comment by KaiKikuchi** [comment]
... have you tried without fres?

**Comment by KaiKikuchi** [comment]
Hello, please test latest build

**Comment by evernife** [comment]
Sorry, school took my time for a while!

Testing! :D

**Comment by evernife** [comment]
Same thing, I can sell normal claims, but not subclaims.
![image](https://cloud.githubusercontent.com/assets/11357801/10031987/b63d65c6-6156-11e5-8c39-2c6f4bff74bf.png)

**Comment by KaiKikuchi** [comment]
Hopefully fixed xD

**Comment by evernife** [comment]
Fixed! :smile:

**Comment by runescapejon** [comment]
the subclaim's ain't fixed
