### ISSUE TITLE
Locale_Config File (enhancement)

### ISSUE THREAD

**Issue by evernife** [KaiKikuchi/GPPRealEstate#2]
Add the texts of the plugin in a config file, in my case, i want to translate to Brazilian Portuguese, having the locale file it would be more easy to everyone who wants to translate to his own language.

*(Low priority)*

**Comment by KaiKikuchi** [comment]
Added both suggestions. It's totally untested.

**Comment by evernife** [comment]
I will test

**Comment by evernife** [comment]
The plugin stopped from working entirely.
Doesn't even create the config folder.

http://pastebin.com/7fmqUDks

**Comment by KaiKikuchi** [comment]
Hopefully fixed

**Comment by evernife** [comment]
Still having problems;

http://pastebin.com/n30jAFPB

**Comment by KaiKikuchi** [comment]
Hopefully fixed. Removed the dumb custom config loader.
https://github.com/KaiKikuchi/GPPRealEstate/releases/tag/v.0.9.5alpha

**Comment by evernife** [comment]
The folder exist now, but is still not working.

http://pastebin.com/BaZNh1rA

**Comment by KaiKikuchi** [comment]
https://github.com/KaiKikuchi/GPPRealEstate/releases/tag/v.0.9.6

I did some test this time xD

**Comment by evernife** [comment]
Now its working.

But the subclaims of adminclaims are not working
