### ISSUE TITLE
Leasing/Renting

### ISSUE THREAD

**Issue by idnthvn** [KaiKikuchi/GPPRealEstate#4]
I know this was a request a long time ago with the original GP, in which they implemented later. I see the option is there, but when placing sign's there is a "not yet implemented"
If there is a way this could be added, i would gladly do a youtube video on the plugin
Please keep up the good work. :) and thank you for taking on the GP project

**Comment by KaiKikuchi** [comment]
Hello, thank you for your suggestion. Lately I'm very busy with a lot of big projects, but I can do this when I get some time. I hope you can wait!

**Comment by idnthvn** [comment]
Oh i totally understand. I am good with computers and figuring out computer issues, Just not computer programming, I keep trying to learn but i am a visual learner which makes it hard to do any online class's. Hopefully one day i can help others with bugs.

**Comment by runescapejon** [comment]
is this being added ?

**Comment by KaiKikuchi** [comment]
It will be added at some point. Maybe sooner if someone makes a request for it with some donation... :P

**Comment by spannerman79** [comment]
Not a great amount but at least something @KaiKikuchi - check your paypal/gmail.

**Comment by KaiKikuchi** [comment]
Thanks for your donation! :)

**Comment by KaiKikuchi** [comment]
Most of the work got done (I've been working on it the entire day).

I just have to test it and fix all the issues.

**Comment by spannerman79** [comment]
Take your time :smile: literally no rush or pressure - I know you do good work hence my little (a bit late) contribution.

**Comment by runescapejon** [comment]
@KaiKikuchi  i have donated $5 usd, same it's not much but greatly appreciate of all of your work for your plugins <3

**Comment by KaiKikuchi** [comment]
Hey, thank you for your support! I hope to be able to complete the new version tomorrow.

**Comment by KaiKikuchi** [comment]
Okay I tested and fixed some issue. This is the first dev/alpha release that supports claims/subclaims renting/leasing: https://github.com/KaiKikuchi/GPPRealEstate/releases/tag/1.0-DEV-1

**Comment by runescapejon** [comment]
how do i make a rent sign for it?

**Comment by KaiKikuchi** [comment]
Type rent (or one of the words specified on the config file after "Renting:") on the third line

**Comment by runescapejon** [comment]
'06.08 19:30:36 [Server] INFO [GPPRealEstate] Rent or sell line: Rent
06.08 19:30:36 [Server] INFO [GPPRealEstate] leaseleasingfor lease
06.08 19:30:36 [Server] INFO [GPPRealEstate] runescapejon has made a Claim (id 388) for Sell at [CraftWorld{name=world}, X: 548, Y: 65, Z: -486] Price: 500 '
and it keep saying selling doesn't make sense

**Comment by KaiKikuchi** [comment]
You have to delete your previous config file.

**Comment by runescapejon** [comment]
Got it thanks

**Comment by runescapejon** [comment]
is there a way to change expire dates ? i want my to last 30 days
