### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by runescapejon** [KaiKikuchi/GPPRealEstate#6]
Cannot make my subclaim rent or selling when i tried to make a subclaim and make sure that it is my claim it bring up a message saying 
"You can only sell claims you own!" when its clearly my claim
https://gyazo.com/1d70ebaee06194f264f6783425848904
the latest version pre-release 1.0-DEV-1

**Comment by KaiKikuchi** [comment]
https://github.com/KaiKikuchi/GPPRealEstate/releases/tag/1.0-DEV-2
